title: МЕТОД — А # Для name_bar
url_title: МЕТОД — А | Решения для бизнеса
email: mail@method-a.ru
phone: +79310037539
telegram: method_a
telegram_dm: merkoeva_work
whatsapp: 79310037539
baseurl: ""
url: https://method-a.ru
data_url: https://data.method-a.ru

# Пагинация
plugins:
  - jekyll-paginate
  - jekyll-tagging

paginate: 5
paginate_path: "/page/:num/"

# Настройки тегов
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag